routes/web.php
<?php

/*
 * |--------------------------------------------------------------------------
 * | Web Routes
 * |--------------------------------------------------------------------------
 * |
 * | Here is where you can register web routes for your application. These
 * | routes are loaded by the RouteServiceProvider within a group which
 * | contains the "web" middleware group. Now create something great!
 * |
 */

use App\Http\Controllers\HomeController;

Auth::routes();


Route::group([
    'middleware' => 'auth'
], function () {
    Route::get('/change-password', 'HomeController@showChangePasswordForm')->name('change-password');
    Route::post('/password-reset-local', 'HomeController@resetPassword')->name('password-reset-local');

    Route::get('/', 'HomeController@index')->name('default');
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('meal', 'Menu\MealController');
    Route::resource('user', 'Admin\UserController');
    Route::resource('menu', 'Menu\MenuController');
    Route::resource('module', 'Admin\ModuleController');
    Route::get('menu_calendar', 'Menu\MenuController@calendar')->name('menu_calendar');
    Route::resource('booking', 'Booking\BookingController');
    Route::resource('booking_admin', 'Booking\AdminBookingController');
    Route::POST('booking-for-user', 'Booking\AdminBookingController@bookForUser')->name('booking-for-user');
    Route::post('pricing', 'Booking\BookingController@pricing');
    Route::post('booking_book', 'Booking\BookingController@book')->name('booking_book');
    Route::resource('food', 'Menu\FoodController');
    Route::resource('sms', 'SMS\SmsController');
    Route::post('sms_send', 'SMS\SmsController@sendSMS')->name('sms.send');
    Route::resource('student', 'Admin\StudentController');

    Route::get('student_create_import', 'Admin\StudentController@createImport')->name('student_create_import');
    Route::post('student_import', 'Admin\StudentController@Import')->name('student_import');
    Route::get('student_export', 'Admin\StudentController@export')->name('student_export');

    Route::get('user_create_import', 'Admin\UserController@createImport')->name('user_create_import');
    Route::post('user_import', 'Admin\UserController@Import')->name('user_import');
    Route::get('user_export', 'Admin\UserController@export')->name('user_export');

    Route::resource('caterer', 'Admin\CatererController');
    Route::get('get_events', 'Menu\MenuController@getEvents');
    Route::resource('visitor', 'Admin\VisitorController');
    Route::resource('right', 'User\RightController');
    Route::resource('user_group', 'User\UserGroupController');
    Route::resource('role', 'User\RoleController');
    Route::get('role-edit/{role}', 'User\RoleController@edit')->name('role-edit');
    Route::post('modify-role/{role}', 'User\RoleController@modify')->name('modify-role');
    Route::post('delete-role/{role}', 'User\RoleController@delete')->name('delete-role');

    Route::resource('report', 'Admin\ReportsController');

    Route::get('booking-report', 'Admin\ReportsController@bookingReport')->name('booking-report');
    Route::get('booking-checklist', 'Admin\ReportsController@bookingChecklist')->name('booking-checklist');

    Route::post('rpt-booking-report', 'Admin\ReportsController@bookingReportLoad')->name('rpt-booking-report');
    Route::post('rpt-booking-checklist', 'Admin\ReportsController@bookingChecklistLoad')->name('rpt-booking-checklist');

    Route::get('/test', 'HomeController@test');
});

/*
 * Custom accessors
 *
 */
Route::get('/gates', 'HomeController@getGates')->name('gates');
Route::get('/modules', 'HomeController@getModules')->name('modules');
Route::get('/permissions', 'HomeController@getPermission')->name('permissions');
Route::get('/roles', 'HomeController@getRoles')->name('roles');

Route::POST('/StlMealBookingReport', 'Admin\ReportsController@rptBooking')->name('StlMealBookingReport');
Route::POST('/rpt_users', 'Admin\ReportsController@rptUsers')->name('rpt_users');




// Route::get('/test', 'HomeController@test');


/**
 * Download Route
 * 
 * Route for templates download
 */

// Route::get('download/{filename}', function ($filename) {
//     // Check if file exists in app/storage/file folder
//     $file_path = storage_path() . '/file/' . $filename;
//     if (file_exists($file_path)) {
//         // Send Download
//         return Response::download($file_path, $filename, [
//             'Content-Length: ' . filesize($file_path)
//         ]);
//     } else {
//         // Error
//         exit('Requested file does not exist on our server!');
//     }
// })->where('filename', '[A-Za-z0-9\-\_\.]+');

app/Http/Controllers/Reports/report.blade.php
<?php
require_once "SalesByCustomer.php";

$salesByCustomer = new SalesByCustomer;
$salesByCustomer->run()->render();

resources/views/caterer_create.blade.php
<form role="form">
    @csrf
    <div class="form-group">
        <label for="title">Full Name<i class="text-danger">*</i></label>
        <input type="text" class="form-control" id="title" name="title" placeholder="enter name ...">
        <label class="error-title"></label>
    </div>
    <div class="form-group">
        <label for="phone">Phone</label>
        <input type="text" class="form-control" id="phone" name="phone" placeholder="phone...">
        <label class="error-phone"></label>
    </div>
    <div class="form-group">
        <label for="password">Address</label>
        <textarea class="form-control" id="address" name="address" placeholder="address ..."></textarea>
        <label class="error-address"></label>
    </div>
   
    <div class="form-group">
        <label for="active">Active<i class="text-danger">*</i></label>
        <select class="form-control" id="active" name="active">
            <option value=1 selected>Yes</option>
            <option value="0">No</option>
        </select>
        <label class="error-active"></label>
    </div>

    <button type="button" data-dismiss="modal" class="btn btn-default pull-left"><i class="fa fa-times" ></i> &nbsp; Exit</button>
    <button type="button" id="add" class="btn btn-success pull-right"><i class="fa fa-check" ></i> &nbsp; Submit</button>
    <br><br>
</form>


<script type="text/javascript">
// Craete module

$("#add").click(function() {
    $.ajax({
        type: 'POST',
        url: '{{ route('caterer.store') }}',
        data: {
            '_token': $('input[name=_token]').val(),
            'title': $('input[name=title]').val(),
            'phone': $('input[name=phone]').val(),
            'address': $('textarea[name=address]').val(),
            'active': $('select[name=active]').val(),
        },
        success: function(data) {
            if (data.errors) {
                console.log(data.errors);
                if (data.errors.title) {
                    $('.error-title').removeClass('hidden').addClass('text-danger');
                    $('#title').addClass('has-error');
                    $('.error-title').text(data.errors.title);
                }else if (data.errors.phone) {
                    $('.error-phone').removeClass('hidden').addClass('text-danger');
                    $('#phone').addClass('has-error');
                    $('.error-phone').text(data.errors.phone);
                }else if (data.errors.address) {
                    $('.error-address').removeClass('hidden').addClass('text-danger');
                    $('#address').addClass('has-error');
                    $('.error-address').text(data.errors.address);
                }else if (data.errors.active) {
                    $('.error-active').removeClass('hidden').addClass('text-danger');
                    $('#active').addClass('has-error');
                    $('.error-active').text(data.errors.active);
                }
            } else {
                console.log(data);
                location.reload();
            }
        },
    });
});
</script>

resources/views/caterer_edit.blade.php
<form role="form">
    @csrf
    <div class="form-group">
        <label for="id">ID<i class="text-danger">*</i></label>
        <input type="text" class="form-control" id="id" name="id" disabled>
        <label class="error-id"></label>
    </div>
    <div class="form-group">
        <label for="title">Full Name<i class="text-danger">*</i></label>
        <input type="text" class="form-control" id="title" name="title" placeholder="enter name ...">
        <label class="error-title"></label>
    </div>
    <div class="form-group">
        <label for="phone">Phone</label>
        <input type="text" class="form-control" id="phone" name="phone" placeholder="phone...">
        <label class="error-phone"></label>
    </div>
    <div class="form-group">
        <label for="password">Address</label>
        <textarea class="form-control" id="address" name="address" placeholder="address ..."></textarea>
        <label class="error-address"></label>
    </div>
   
    <div class="form-group">
        <label for="active">Active<i class="text-danger">*</i></label>
        <select class="form-control" id="active" name="active">
            <option value=1 selected>Yes</option>
            <option value="0">No</option>
        </select>
        <label class="error-active"></label>
    </div>
    
    <button type="button" data-dismiss="modal" class="btn btn-default pull-left"><i class="fa fa-times" ></i> &nbsp; Exit</button>
    <button type="button" id="add_module" class="btn btn-success pull-right"><i class="fa fa-check" ></i> &nbsp; Submit</button>
    <br><br>
</form>


<script type="text/javascript">
// Craete module

$("#add_module").click(function() {
	var url = '{{ route("caterer.update", ["caterer"=>":caterer"]) }}';
    $.ajax({
        type: 'PATCH',
        url: url.replace(":caterer", $('input[name=id]').val()),
        data: {
        	 '_token': $('input[name=_token]').val(),
             'title': $('input[name=title]').val(),
             'phone': $('input[name=phone]').val(),
             'address': $('textarea[name=address]').val(),
             'active': $('select[name=active]').val(),
        },
        success: function(data) {
            if (data.errors) {
                console.log(data.errors);
                if (data.errors.title) {
                    $('.error-title').removeClass('hidden').addClass('text-danger');
                    $('#title').addClass('has-error');
                    $('.error-title').text(data.errors.title);
                }else if (data.errors.phone) {
                    $('.error-phone').removeClass('hidden').addClass('text-danger');
                    $('#phone').addClass('has-error');
                    $('.error-phone').text(data.errors.phone);
                }else if (data.errors.address) {
                    $('.error-address').removeClass('hidden').addClass('text-danger');
                    $('#address').addClass('has-error');
                    $('.error-address').text(data.errors.address);
                }else if (data.errors.active) {
                    $('.error-active').removeClass('hidden').addClass('text-danger');
                    $('#active').addClass('has-error');
                    $('.error-active').text(data.errors.active);
                }
            } else {
                console.log(data);
                location.reload();
            }
        },
    });
});
</script>

resources/views/modules.blade.php
@extends('layouts.main') @section('content')
<!--main content start-->
<section id="main-content">
	<section class="wrapper">
		<!-- page start-->
		<div class="row">
			<div class="col-sm-12">
				<section class="panel">
					<header class="panel-heading">
						Modules View <span class="tools pull-right"> <a href="javascript:;"
							class="fa fa-chevron-down"></a> <a href="javascript:;"
							class="fa fa-cog"></a> <a href="javascript:;" class="fa fa-times"></a>
						</span>
					</header>
					<div class="panel-body">
						<div class="adv-table editable-table ">
							<div class="clearfix">
								<div class="btn-group pull-right">
									<button
									type="button" id="newresource"
									class="btn btn-default"
									data-toggle="modal"
									data-target="#dynamic-modal"
									data-path="{{ route('module.create') }}"
									>
										<i class="fa fa-plus"></i> Add New
									</button>
								</div>
								<div class="btn-group pull-left">
									<button class="btn btn-default dropdown-toggle"
										data-toggle="dropdown">
										Tools <i class="fa fa-angle-down"></i>
									</button>

								</div>
							</div>
							<div class="space15"></div>
							<table class="table table-striped table-hover table-bordered"
								id="editable-sample">
								<thead>
									<tr>
										<th>No</th>
										<th>Name</th>
										<th>Color</th>
<!-- 										<th>Detail</th> -->
										<th>Order</th>
										<th>Link</th>
										<th>Icon</th>
										<th>ParentId</th>
										<th>IsRoot</th>
										<th>Active</th>
										<th>Action</th>
									</tr>
								</thead>
								<tbody>
									@foreach($resources as $resource)
									<tr class="">
										<td>{{$resource->id}}</td>
										<td>{{$resource->title}}</td>
										<td>{{$resource->color}}</td>
<!-- 										<td>{{$resource->detail}}</td> -->
										<td>{{$resource->order}}</td>
										<td>{{$resource->link}}</td>
										<td>{{$resource->icon}}</td>
										<td>{{$resource->id_parent}}</td>
										<td>{{$resource->is_root}}</td>
										<td>{{$resource->active}}</td>
										<td class="text-right"><a href="#"
											class="show-modal btn btn-default "
											data-id="{{$resource->id}}"
											data-title="{{$resource->title}}"
											data-color="{{$resource->color}}"
											data-detail="{{$resource->detail}}"
											data-order="{{$resource->order}}"
											data-link="{{$resource->link}}"
											data-icon="{{$resource->icon}}"
											data-id_parent="{{$resource->id_parent}}"
											data-is_root="{{$resource->is_root}}"
											data-active="{{$resource->active}}"
											data-path="{{ route('module.show',['resource'=>$resource->id]) }}"
											data-toggle="modal"
											data-target="#dynamic-modal"
											> <i class="fa fa-eye"></i>
										</a> <a href="#" class="edit-modal btn btn-default"
											data-id="{{$resource->id}}"
											data-title="{{$resource->title}}"
											data-color="{{$resource->color}}"
											data-detail="{{$resource->detail}}"
											data-order="{{$resource->order}}"
											data-link="{{$resource->link}}"
											data-icon="{{$resource->icon}}"
											data-id_parent="{{$resource->id_parent}}"
											data-is_root="{{$resource->is_root}}"
											data-active="{{$resource->active}}"
											data-path="{{ route('module.edit',['resource'=>$resource->id]) }}"
											data-toggle="modal"
											data-target="#dynamic-modal"
											><i class="fa fa-pencil"></i>
										</a> <a href="#" class="delete-modal btn btn-danger"
											data-id="{{$resource->id}}"
											data-title="{{$resource->title}}"
											data-color="{{$resource->color}}"
											data-detail="{{$resource->detail}}"
											data-order="{{$resource->order}}"
											data-link="{{$resource->link}}"
											data-icon="{{$resource->icon}}"
											data-id_parent="{{$resource->id_parent}}"
											data-is_root="{{$resource->is_root}}"
											data-active="{{$resource->active}}"
											><i class="fa fa-trash-o"></i>
										</a></td>

									</tr>
									@endforeach
								</tbody>
							</table>
						</div>
					</div>
				</section>

			</div>
		</div>
		<!-- page end-->
	</section>

</section>
<!--main content end-->


<!-- My Dynamic Modal -->
<div id="dynamic-modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
    aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <span class=" text-info pull-left">{{env('APP_NAME')}}</span>
                <button type="button" class="btn btn-danger btn-md pull-right btn-round"
                    data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
                <!-- Body content will come here -->
            </div>
            <div class="modal-footer">
                {{env('APP_NAME')}}
            </div>
        </div>
    </div>
</div>
<!-- End modal -->

<script type="text/javascript">

$("#newresource").click(function () {
    $.ajax({
        type: 'GET',
        url: $(this).data('path'),
        success: function (data) {
            $('#dynamic-modal div.modal-body').html(data); 
        },
    });
});

//form Delete function
$(document).on('click', '.delete-modal', function() {
   $('#dynamic-modal').addClass('modal-danger');
   $('.modal-body').html('<h4 class="text-danger">Delete this item? ' + $(this).data('id') + ':' + $(this).data('title')+'</h4><input type="hidden" class="id">');
    $('.modal-footer').html('<button type="button" id="calcel" data-dismiss="modal" class="btn btn-primary" >Cancel</button> <button type="button" id="delete" class="delete btn btn-danger" >Delete</button>');
    $('#dynamic-modal').modal('show');
    $('.id').text($(this).data('id'));
});

$('.modal-footer').on('click', '.delete', function() {
	 var url = '{{ route("module.destroy", ["id"=>":id"]) }}';
    $.ajax({
        type: 'DELETE',
        url: url.replace(":id", $('.id').text()),
        data: {
            '_token': $('input[name=_token]').val(),
            'id': $('.id').text()
        },
        success: function(data) {
            location.reload();
        }
    });
});
//Action Edit/Update
$(document).on('click', '.edit-modal', function() {
	var name = $(this).data('name');
	var id = $(this).data('id');
	var title = $(this).data('title');
	var color = $(this).data('color');
	var order = $(this).data('order');
	var link = $(this).data('link');
	var icon = $(this).data('icon');
	var active = $(this).data('active');
	var root = $(this).data('root');
	var parent = $(this).data('parent');
	var detail = $(this).data('detail');
	
	$.ajax({
        type: 'GET',
        url: $(this).data('path'),
        success: function (data) {
            $('#dynamic-modal div.modal-body').html(data); 
            $('input[name=id]').val(id);
            $('input[name=title]').val(title);
            $('input[name=color]').val(color);
            $('input[name=order]').val(order);
            $('input[name=link]').val(link);
            $('input[name=icon]').val(icon);
            $('select[name=active]').val(active);
            $('select[name=root]').val(root);
            $('select[name=parent]').val(parent);
            $('textarea[name=detail]').val(detail);
        },
    });
});

//Show function
$(document).on('click', '.show-modal', function() {
	var name = $(this).data('name');
	var id = $(this).data('id');
	var email = $(this).data('email');
	var role = $(this).data('role');
	var active = $(this).data('active');
	var phone = $(this).data('phone');
	
	$.ajax({
        type: 'GET',
        url: $(this).data('path'),
        success: function (data) {
            $('#dynamic-modal div.modal-body').html(data); 
            $('#id').text(id);
            $('#name').text(name);
            $('#email').text(email);
            $('#role').text(role);
            $('#active').text(active);
            $('#phone').text(phone);
        },
    });
});

</script>
@endsection

resources/views/user_group_edit.blade.php
<form role="form">
    @csrf
    <div class="form-group">
        <label for="id">ID<i class="text-danger">*</i></label>
        <input type="text" class="form-control" id="id" name="id" disabled>
    </div>
    <div class="form-group">
        <label for="title">Title<i class="text-danger">*</i></label>
        <input type="title" class="form-control" id="title" name="title" placeholder="Enter title ...">
        <label class="error-title"></label>
    </div>
    
    <div class="form-group">
        <label for="detail">Detail</label>
        <textarea class="form-control" id="detail" name="detail" placeholder="Describe here ..."></textarea>
        <label class="error-detail"></label>
    </div>
    
    <div class="form-group">
        <h4>Group Rights</h4>
        <hr>
            @foreach($rights as $right)
            <div class="checkbox">
            <label  class="form-group" >
                <input type="checkbox" value="{{$right->id}}"
                @if(in_array($right->title,$given_rights))
                	checked
                @endif
                >
                &nbsp; {{$right->detail}}
            </label>
            </div>
            @endforeach
            <br>
    </div>


    <div class="text-right">
        <button type="button" id="add_right" class="btn btn-primary"><i class="fa fa-check" ></i>Submit</button>
    </div>
    </form>


<script type="text/javascript">
// Craete right

$("#add_right").click(function() {

	var rights= { 'group_rights' : []};

    $(":checked").each(function() {
      rights['group_rights'].push($(this).val());
    });
    console.log(rights);

	
	var url = '{{ route("user_group.update", ["right"=>":right"]) }}';
    $.ajax({
        type: 'PATCH',
        url: url.replace(":right", $('input[name=id]').val()),
        data: {
            '_token': $('input[name=_token]').val(),
            'title': $('input[name=title]').val(),
            'detail': $('textarea[name=detail]').val(),
            'rights': rights['group_rights'],
        },
        success: function(data) {
            if (data.errors) {
                console.log(data.errors);
                if (data.errors.title) {
                    $('.error-title').removeClass('hidden').addClass('text-danger');
                    $('#title').addClass('has-error');
                    $('.error-title').text(data.errors.title);
                } else if (data.errors.detail) {
                    $('.error-detail').removeClass('hidden').addClass('text-danger');
                    $('#detail').addClass('has-error');
                    $('.error-detail').text(data.errors.detail);
                }
            } else {
                console.log(data);
                location.reload();
            }
        },
    });
});
</script>

resources/views/users.blade.php
@extends('layouts.main') @section('content')
<!--main content start-->
<section id="main-content">
	<section class="wrapper">
		<!-- page start-->
		<div class="row">
			<div class="col-sm-12">
				<section class="panel">
					<header class="panel-heading">
						User Table <span class="tools pull-right"> <a href="javascript:;"
							class="fa fa-chevron-down"></a> <a href="javascript:;"
							class="fa fa-cog"></a> <a href="javascript:;" class="fa fa-times"></a>
						</span>
					</header>
					<div class="panel-body">
						<div class="adv-table editable-table ">
							<div class="clearfix">
								<div class="btn-group pull-right">
									<button
									type="button" id="newuser"
									class="btn btn-success"
									data-toggle="modal"
									data-target="#dynamic-modal"
									data-path="{{ route('user.create') }}"
									>
									<i class="fa fa-plus"></i> Add New User
									</button>
									<button
									type="button" id="import"
									class="btn btn-success"
									data-toggle="modal"
									data-target="#dynamic-modal"
									data-path="{{ route('user_create_import') }}"
									>
									<i class="fa fa-download"></i> Import Excel
									</button>
									<button
									type="button" id="export"
									class="btn btn-success"
									data-path="{{ route('user_export') }}"
									>
									<i class="fa fa-file"></i> Export Excel
									</button>
								</div>

							</div>
							<div class="space15"></div>
							<table class="table table-striped table-hover table-bordered"
								id="editable-sample">
								<thead>
									<tr>
										<th>No</th>
										<th>Name</th>
										<th>Payroll No</th>
										<th>Email</th>
										<th>Role</th>
										<th>Phone</th>
										<th>Active</th>
										<th>Actions</th>
									</tr>
								</thead>
								<tbody>
									@foreach($users as $user)
									@php
    									if($user->roles->first()){
    										$user_role = $user->roles->first();
    										$role = $user_role->title;
    									}else{
    										$role = 'Not set';
    									}
    								@endphp
									<tr class="">
										<td>{{$user->id}}</td>
										<td>{{$user->name}}</td>
										<td>{{$user->payroll}}</td>
										<td>{{$user->email}}</td>
										<td>{{$role}}</td>
										<td>{{$user->phone}}</td>
										<td>{{$user->active}}</td>
										<td class="text-right"><a href="#"
											class="show-modal btn btn-default "
											data-id="{{$user->id}}"
											data-name="{{$user->name}}"
											data-email="{{$user->email}}"
											data-role="{{$user_role->id}}"
											data-phone="{{$user->phone}}"
											data-payroll="{{$user->payroll}}"
											data-active="{{$user->active}}"
											data-path="{{ route('user.show',['user'=>$user->id]) }}"
											data-toggle="modal"
											data-target="#dynamic-modal"
											> <i class="fa fa-eye"></i>
										</a> <a href="#" class="edit-modal btn btn-default"
											data-id="{{$user->id}}" 
											data-name="{{$user->name}}"
											data-username="{{$user->username}}"
											data-email="{{$user->email}}"
											data-role="{{$user_role->id}}"
											data-phone="{{$user->phone}}" 
											data-active="{{$user->active}}"
											data-path="{{ route('user.edit',['user'=>$user->id]) }}"
											data-payroll="{{$user->payroll}}"
											data-toggle="modal"
											data-target="#dynamic-modal"
											>
											<i class="fa fa-pencil"></i>
										</a>
										<a href="#" class="delete-modal btn btn-danger"
											data-id="{{$user->id}}" 
											data-name="{{$user->name}}"
											data-email="{{$user->email}}" 
											data-role="{{$user_role->id}}"
											data-phone="{{$user->phone}}"
											data-payroll="{{$user->payroll}}"
											data-active="{{$user->active}}">
											<i class="fa fa-trash-o"></i>
										</a></td>

									</tr>
									@endforeach
								</tbody>
							</table>
						</div>
					</div>
				</section>

			</div>
		</div>
		<!-- page end-->
	</section>

</section>
<!--main content end-->


<!-- My Dynamic Modal -->
<div id="dynamic-modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
    aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <span class=" text-info pull-left">{{env('APP_NAME', 'E-Meals')}}</span>
                <button type="button" class="btn btn-danger btn-md pull-right btn-round"
                    data-dismiss="modal">&times;</button>
            </div>
            <div class="modal-body">
                <!-- Body content will come here -->
            </div>
            <div class="modal-footer">
                {{env('APP_NAME')}}
            </div>
        </div>
    </div>
</div>
<!-- End modal -->

<!-- 
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
 -->

<script type="text/javascript">

$("#newuser").click(function () {
    $.ajax({
        type: 'GET',
        url: $(this).data('path'),
        success: function (data) {
            console.log(data);
            $('#dynamic-modal div.modal-body').html(data);
        },
    });
});


//export 
$("#export").click(function () {
	window.location = $(this).data('path');
});


//import 
$("#import").click(function () {
    $.ajax({
        type: 'GET',
        url: $(this).data('path'),
        success: function (data) {
            $('#dynamic-modal div.modal-body').html(data); 
        },
    });
});


//form Delete function
$(document).on('click', '.delete-modal', function() {
   $('#dynamic-modal').addClass('modal-danger');
   $('.modal-body').html('<h4 class="text-danger">Delete this item? ' + $(this).data('id') + ':' + $(this).data('name')+'</h4><input type="hidden" id="id-user">');
    $('.modal-footer').html('<button type="button" id="calcel" data-dismiss="modal" class="btn btn-primary" >Cancel</button> <button type="button" id="delete" class="delete btn btn-danger" >Delete</button>');
    $('#dynamic-modal').modal('show');
    $('#id-user').text($(this).data('id'));
});

$('.modal-footer').on('click', '.delete', function() {
	 var url = '{{ route("user.destroy", ["id"=>":id"]) }}';
    $.ajax({
        type: 'DELETE',
        url: url.replace(":id", $('#id-user').text()),
        data: {
            '_token': $('input[name=_token]').val(),
        },
        success: function(data) {
            console.log(data);
            location.reload();
        }
    });
});
//Action Edit/Update
$(document).on('click', '.edit-modal', function() {
	var name = $(this).data('name');
	var payroll = $(this).data('payroll');
	var id = $(this).data('id');
	var email = $(this).data('email');
	var role = $(this).data('role');
	var active = $(this).data('active');
	var phone = $(this).data('phone');

	$.ajax({
        type: 'GET',
        url: $(this).data('path'),
        success: function (data) {
            console.log(data);
            $('#dynamic-modal div.modal-body').html(data);
            $('input[name=id]').val(id);
            $('input[name=name]').val(name);
            $('input[name=payroll]').val(payroll);
            $('input[name=email]').val(email);
            $('select[name=role]').val(role);
            $('select[name=username]').val(username);
            $('select[name=active]').val(active);
            $('input[name=phone]').val(phone);
        },
    });
});

//Show function
$(document).on('click', '.show-modal', function() {
	var name = $(this).data('name');
	var payroll = $(this).data('payroll');
	var id = $(this).data('id');
	var email = $(this).data('email');
	var role = $(this).data('role');
	var active = $(this).data('active');
	var phone = $(this).data('phone');
	var payroll = $(this).data('payroll');

	$.ajax({
        type: 'GET',
        url: $(this).data('path'),
        success: function (data) {
            $('#dynamic-modal div.modal-body').html(data);
            $('#id').text(id);
            $('#name').text(name);
            $('#payroll').text(payroll);
            $('#email').text(email);
            $('#role').text(role);
            $('#active').text(active);
            $('#phone').text(phone);
        },
    });
});

</script>
@endsection