routes/web.php
<?php

/*
 * |--------------------------------------------------------------------------
 * | Web Routes
 * |--------------------------------------------------------------------------
 * |
 * | Here is where you can register web routes for your application. These
 * | routes are loaded by the RouteServiceProvider within a group which
 * | contains the "web" middleware group. Now create something great!
 * |
 */

use App\Http\Controllers\HomeController;

Auth::routes();


Route::group([
    'middleware' => 'auth'
], function () {
    Route::get('/change-password', 'HomeController@showChangePasswordForm')->name('change-password');
    Route::post('/password-reset-local', 'HomeController@resetPassword')->name('password-reset-local');

    Route::get('/', 'HomeController@index')->name('default');
    Route::get('/home', 'HomeController@index')->name('home');
    Route::resource('meal', 'Menu\MealController');
    Route::resource('user', 'Admin\UserController');
    Route::resource('menu', 'Menu\MenuController');
    Route::resource('module', 'Admin\ModuleController');
    Route::get('menu_calendar', 'Menu\MenuController@calendar')->name('menu_calendar');
    Route::resource('booking', 'Booking\BookingController');
    Route::resource('booking_admin', 'Booking\AdminBookingController');
    Route::POST('booking-for-user', 'Booking\AdminBookingController@bookForUser')->name('booking-for-user');
    Route::post('pricing', 'Booking\BookingController@pricing');
    Route::post('booking_book', 'Booking\BookingController@book')->name('booking_book');
    Route::resource('food', 'Menu\FoodController');
    Route::resource('sms', 'SMS\SmsController');
    Route::post('sms_send', 'SMS\SmsController@sendSMS')->name('sms.send');
    Route::resource('student', 'Admin\StudentController');

    Route::get('student_create_import', 'Admin\StudentController@createImport')->name('student_create_import');
    Route::post('student_import', 'Admin\StudentController@Import')->name('student_import');
    Route::get('student_export', 'Admin\StudentController@export')->name('student_export');

    Route::get('user_create_import', 'Admin\UserController@createImport')->name('user_create_import');
    Route::post('user_import', 'Admin\UserController@Import')->name('user_import');
    Route::get('user_export', 'Admin\UserController@export')->name('user_export');

    Route::resource('caterer', 'Admin\CatererController');
    Route::get('get_events', 'Menu\MenuController@getEvents');
    Route::resource('visitor', 'Admin\VisitorController');
    Route::resource('right', 'User\RightController');
    Route::resource('user_group', 'User\UserGroupController');
    Route::resource('role', 'User\RoleController');
    Route::get('role-edit/{role}', 'User\RoleController@edit')->name('role-edit');
    Route::post('modify-role/{role}', 'User\RoleController@modify')->name('modify-role');
    Route::post('delete-role/{role}', 'User\RoleController@delete')->name('delete-role');

    Route::resource('report', 'Admin\ReportsController');

    Route::get('booking-report', 'Admin\ReportsController@bookingReport')->name('booking-report');
    Route::get('booking-checklist', 'Admin\ReportsController@bookingChecklist')->name('booking-checklist');

    Route::post('rpt-booking-report', 'Admin\ReportsController@bookingReportLoad')->name('rpt-booking-report');
    Route::post('rpt-booking-checklist', 'Admin\ReportsController@bookingChecklistLoad')->name('rpt-booking-checklist');

    Route::get('/test', 'HomeController@test');
});

/*
 * Custom accessors
 *
 */
Route::get('/gates', 'HomeController@getGates')->name('gates');
Route::get('/modules', 'HomeController@getModules')->name('modules');
Route::get('/permissions', 'HomeController@getPermission')->name('permissions');
Route::get('/roles', 'HomeController@getRoles')->name('roles');

Route::POST('/StlMealBookingReport', 'Admin\ReportsController@rptBooking')->name('StlMealBookingReport');
Route::POST('/rpt_users', 'Admin\ReportsController@rptUsers')->name('rpt_users');




// Route::get('/test', 'HomeController@test');


/**
 * Download Route
 * 
 * Route for templates download
 */

// Route::get('download/{filename}', function ($filename) {
//     // Check if file exists in app/storage/file folder
//     $file_path = storage_path() . '/file/' . $filename;
//     if (file_exists($file_path)) {
//         // Send Download
//         return Response::download($file_path, $filename, [
//             'Content-Length: ' . filesize($file_path)
//         ]);
//     } else {
//         // Error
//         exit('Requested file does not exist on our server!');
//     }
// })->where('filename', '[A-Za-z0-9\-\_\.]+');

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="ThemeBucket">
    <link rel="shortcut icon" href="images/favicon.html">

    <title>{{ config('app.name', 'MealBS') }}</title>
    
    <link rel="shortcut icon" href="images/favicon.html">
    <title>BucketAdmin</title>
    <!--Core CSS -->
	<script src="{{ asset('bucket/js/jquery.js') }}"></script>
    <script src="{{ asset('bucket/js/jquery-ui/jquery-ui-1.10.1.custom.min.js') }}"></script>
    <script src="{{ asset('bucket/bs3/js/bootstrap.min.js') }}"></script>
    
    <link href="{{ asset('bucket/bs3/css/bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ asset('bucket/js/jquery-ui/jquery-ui-1.10.1.custom.min.css') }}" rel="stylesheet">
    <link href="{{ asset('bucket/css/bootstrap-reset.css') }}" rel="stylesheet">
    <link href="{{ asset('bucket/font-awesome/css/font-awesome.css') }}" rel="stylesheet">
    <link href="{{ asset('bucket/js/jvector-map/jquery-jvectormap-1.2.2.css') }}" rel="stylesheet">
    <link href="{{ asset('bucket/css/clndr.css') }}" rel="stylesheet">
    <!--clock css-->
    <link href="{{ asset('bucket/js/css3clock/css/style.css') }}" rel="stylesheet">
    <!--Morris Chart CSS -->
    <link rel="stylesheet" href="{{ asset('bucket/js/morris-chart/morris.css') }}">
    <!-- Custom styles for this template -->
    <link href="{{ asset('bucket/css/style.css') }}" rel="stylesheet">
    <link href="{{ asset('bucket/css/style-responsive.css') }}" rel="stylesheet"/>
    
    
    <link href="{{ asset('css/components-rounded.css') }}" rel="stylesheet">
    <script src="{{ asset('js/spinner.js') }}"></script>
    
     @toastr_css
     
</head>
<body>
<!-- BEGIN PAGE SPINNER -->
	<div class="page-spinner-bar" id="page-spinner-bar">
		<div class="bounce1"></div>
		<div class="bounce2"></div>
		<div class="bounce3"></div>
	</div>
	<!-- END PAGE SPINNER -->


@toastr_js
@toastr_render

    <section id="container">
        <!--header start-->
        @include('layouts.header')
        <!--header end-->

        @include('layouts.sidebar')

        @yield('content')
        
    </section>

<!-- Placed js at the end of the document so the pages load faster -->
<!--Core js-->
<script src="{{ asset('bucket/js/jquery.js') }}"></script>
<script src="{{ asset('bucket/bs3/js/bootstrap.min.js') }}"></script>
<script src="{{ asset('bucket/js/jquery-ui/jquery-ui-1.10.1.custom.min.js') }}"></script>
<script src="{{ asset('bucket/js/jquery.dcjqaccordion.2.7.js') }}"></script>
<script src="{{ asset('bucket/js/jquery.scrollTo.min.js') }}"></script>
<script src="{{ asset('bucket/js/jQuery-slimScroll-1.3.0/jquery.slimscroll.js') }}"></script>
<script src="{{ asset('bucket/js/jquery.nicescroll.js') }}"></script>

<!--[if lte IE 8]>
<script language="javascript" type="text/javascript" src="js/flot-chart/excanvas.min.js"></script><![endif]-->
<script src="{{ asset('bucket/js/skycons/skycons.js') }}"></script>
<script src="{{ asset('bucket/js/jquery.scrollTo/jquery.scrollTo.js') }}"></script>
<script src="{{ asset('bucket/cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.3/jquery.easing.min.js') }}"></script>
<script src="{{ asset('bucket/js/calendar/clndr.js') }} "></script>
<script src="{{ asset('bucket/cdnjs.cloudflare.com/ajax/libs/underscore.js/1.5.2/underscore-min.js') }}"></script>
<script src="{{ asset('bucket/js/calendar/moment-2.2.1.js')}} "></script>
<script src="{{ asset('bucket/js/evnt.calendar.init.js') }}"></script>
<script src="{{ asset('bucket/js/jvector-map/jquery-jvectormap-1.2.2.min.js') }}"></script>
<script src="{{ asset('bucket/js/jvector-map/jquery-jvectormap-us-lcc-en.js') }}"></script>
<script src="{{ asset('bucket/js/gauge/gauge.js') }}"></script>
<!--clock init-->
<script src="{{ asset('bucket/js/css3clock/js/css3clock.js') }}"></script>
<!--Easy Pie Chart-->
<script src="{{ asset('bucket/js/easypiechart/jquery.easypiechart.js') }}"></script>
<!--Sparkline Chart-->
<script src="{{ asset('bucket/js/sparkline/jquery.sparkline.js') }}"></script>
<!--Morris Chart-->
<script src="{{ asset('bucket/js/morris-chart/morris.js') }}"></script>
<script src="{{ asset('bucket/js/morris-chart/raphael-min.js') }}"></script>
<!--jQuery Flot Chart-->
<script src="{{ asset('bucket/js/flot-chart/jquery.flot.js') }}"></script>
<script src="{{ asset('bucket/js/flot-chart/jquery.flot.tooltip.min.js') }}"></script>
<script src="{{ asset('bucket/js/flot-chart/jquery.flot.resize.js') }}"></script>
<!--<script src="js/flot-chart/jquery.flot.pie.resize.js"></script>-->
<script src="{{ asset('bucket/js/flot-chart/jquery.flot.pie.js') }}"></script>
<script src="{{ asset('bucket/js/flot-chart/jquery.flot.animator.min.js') }}"></script>
<script src="{{ asset('bucket/js/flot-chart/jquery.flot.growraf.js') }}"></script>

<script src="{{ asset('bucket/js/dashboard.js') }}"></script>
<script src="{{ asset('bucket/js/jquery.customSelect.min.js') }}" ></script>
<!--common script init for all pages-->
<script src="{{ asset('bucket/js/scripts.js') }}"></script>

<script type="text/javascript"
	src="{{ asset('bucket/js/data-tables/jquery.dataTables.js') }}"></script>
<script type="text/javascript"
	src="{{ asset('bucket/js/data-tables/DT_bootstrap.js') }}"></script>

<!--common script init for all pages-->
<script src="{{ asset('bucket/js/scripts.js') }}"></script>

<!--script for this page only-->
<script src="{{ asset('bucket/js/table-editable.js') }}"></script>
	
</body>

</html>

resources/views/layouts/header.blade.php
<?php

use App\User;

$user = User::find(Auth::user()->id);
?>

<!--header start-->
<header class="header fixed-top clearfix">
	<!--logo start-->
	<div class="brand">

		<a href="#" class="logo col-sm-12 col-md-12 col-lg-12 col-xl-12">
			<img src="{{ asset('bucket/images/STL Logo_.png') }}" alt="eMeal" class="img-fluid responsive" style="margin: -8% 0 0 12%; min-width:10%; max-width:55%;">
		</a>
		<div class="sidebar-toggle-box">
			<div class="fa fa-bars"></div>
		</div>
	</div>
	<!--logo end-->

	<div class="nav notify-row" id="top_menu">
		<!--  notification start -->

		<!--  notification end -->
	</div>
	<div class="top-nav clearfix">
		<!--search & user info start-->
		<ul class="nav pull-right top-menu">
			<!-- <li>
				<input type="text" class="form-control search" placeholder=" Search">
			</li> -->
			<!-- user login dropdown start-->
			<li class="dropdown">
				<a data-toggle="dropdown" class="dropdown-toggle">
					<img alt="" src="{{ asset('bucket/images/user.png') }}">
					<span class="username">{{Auth::user()->username }}</span>
					<b class="caret"></b>
				</a>
				<ul class="dropdown-menu extended logout">
					<li><a href="#" id="user-profile" data-toggle="modal" data-target="#profile-modal"><i class=" fa fa-suitcase"></i>Profile</a></li>
					<!--<li><a href="#"><i class="fa fa-cog"></i> Settings</a></li> -->
					<li><a href="{{ route('logout') }}" onclick="event.preventDefault(); document.getElementById('logout-form').submit();"><i class="fa fa-key"></i> Log Out</a></li>
					<form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">@csrf</form>
				</ul>
			</li>
			<!-- user login dropdown end -->
			<!-- <li>
				<div class="toggle-right-box">
					<div class="fa fa-bars"></div>
				</div>
			</li> -->
		</ul>
		<!--search & user info end-->
	</div>
</header>

<!-- User profile modal -->
<div class="modal fade" id="profile-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
	<div class="modal-dialog modal-dialog-centered" role="document">
		<div class="modal-content">

			<div class="modal-header">
				<h5 class="modal-title pull-left" id="exampleModalLongTitle">User Profile</h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
					<span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body clearfix">
				<aside class="profile-nav alt">
					<section class="panel">
						<div class="user-heading alt bg-info text-center">
							<a href="#">
								<img alt="" src="{{ asset('bucket/images/user.png') }}">
							</a>
							<h1>{{$user->FIRST_NAME }}</h1>
							<p>{{ $user->roles[0]['title'] }}</p>
						</div>

						<div class="" id="view-section">
							<ul class="nav nav-pills nav-stacked">
								<li><a href="javascript:;"> <i class="fa fa-tag"></i> Full Name : <span class="text-info text-lg pull-right">{{ $user->FIRST_NAME }} {{ $user->LAST_NAME }}</span></a></li>
								<li><a href="javascript:;"> <i class="fa fa-envelope-o"></i> Email Address : <span class="text-info text-lg pull-right">{{ $user->email }}</span></a></li>
								<li><a href="javascript:;"> <i class="fa fa-list"></i> Payroll # : <span class="text-info text-lg pull-right">{{ $user->USER_ID }}</span></a></li>
								<li><a href="javascript:;"> <i class="fa fa-phone"></i> Phone # : <span class="text-info text-lg pull-right">{{Auth::user()->PHONE_NO }}</span></a></li>
								<li><a href="javascript:;"> <i class="fa fa-users"></i> Role : <span class="text-info text-lg pull-right">{{ $user->roles[0]['title'] }}</span></a></li>
							</ul>
						</div>

						<div class="modal-footer">
							<button type="button" class="btn btn-info btn-md border btn-edit-user" id="btn-edit-user"><i class="fa fa-pencil"></i>&nbsp; Edit</button>
						</div>

						<div class="hidden" id="edit-section">
							<div class="form-group col-md-5 col-sm-2">
								<label for="id">User ID<i class="text-danger">*</i></label>
								<input type="text" class="form-control" id="h_id" name="h_id" value="{{$user->id}}" disabled>
								<label class="error-id"></label>
							</div>
							<div class="form-group col-md-7 col-sm-2">
								<label for="name">User Name<i class="text-danger">*</i></label>
								<input type="text" class="form-control" id="h_username" name="h_username" value="{{$user->username}}">
								<label class="error-h_username"></label>
							</div>
							<div class="form-group col-md-6 col-sm-6">
								<label for="name">Full Name<i class="text-danger">*</i></label>
								<input type="text" class="form-control" id="h_name" name="h_name" value="{{$user->name}}">
								<label class="error-h_name"></label>
							</div>
							<div class="form-group col-md-6 col-sm-6">
								<label for="email">Email</label>
								<input type="text" class="form-control" id="h_email" name="h_email" value="{{$user->email}}">
								<label class="error-h_email"></label>
							</div>
							<div class="form-group col-md-6 col-sm-6">
								<label for="phone">Phone</label>
								<input type="text" class="form-control" id="h_phone" name="h_phone" value="{{$user->phone}}">
								<label class="error-h_phone"></label>
							</div>
							<div class="form-group col-md-6 col-sm-6">
								<label for="payroll">Payroll</label>
								<input type="text" class="form-control" id="h_payroll" name="h_payroll" value="{{$user->payroll}}">
								<label class="error-h_payroll"></label>
							</div>
							<div class="form-group col-md-6 col-sm-6">
								<label for="h_password">Password</label>
								<input type="password" class="form-control" id="h_password" name="h_password">
								<label class="error-h_password"></label>
							</div>

							<div class="form-group col-md-6 col-sm-6">
								<label for="h_password_confiormation">Confirm Password</label>
								<input type="password" class="form-control" id="h_password_confirmation" name="h_password_confirmation">
								<label class="error-h_password_confirmation"></label>
							</div>


							<div class="form-group col-md-6 col-sm-6">
								<label for="h_role">Role</label>
								<input type="h_role" class="form-control" id="h_role" name="h_role" value="{{ $user->roles[0]['title'] }}" disabled>
								<label class="error-h_role"></label>
							</div>

							<div class="form-group col-md-6 col-sm-6">
								<button type="button" class="btn btn-success btn-md border" id="btn-update-user"><i class="fa fa-pencil"></i>&nbsp; Update Profile</button>
							</div>
						</div>
					</section>
				</aside>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-white btn-md border " data-dismiss="modal"><i class="fa fa-times"></i>&nbsp; Exit</button>
			</div>
		</div>
	</div>
</div>


<script>
	$(".btn-edit-user").click(function() {
		console.log('user edit clicked');
		$("#edit-section").removeClass('hidden');
		$(this).addClass('hidden');
		$("#view-section").addClass('hidden');
	});



	$("#btn-update-user").click(function() {
		var url = '{{ route("user.update", ["user"=>":user"]) }}';
		$.ajax({
			type: 'PATCH',
			url: url.replace(":user", $('input[name=id]').val()),
			data: {(":user", $('input[name=id]').val()),
			data: {
				'_token': $('input[name=_token]').val(),
				'name': $('input[name=h_name]').val(),
				'username': $('input[name=h_username]').val(),
				'email': $('input[name=h_email]').val(),
				'phone': $('input[name=h_phone]').val(),
				'payroll': $('input[name=h_payroll]').val(),
				'password': $('input[name=h_password]').val(),
				'active': 1,
			},
			success: function(data) {
				if (data.errors) {
					console.log(data.errors);
					if (data.errors.phone) {
						$('.error-phone').removeClass('hidden').addClass('text-danger');
						$('#phone').addClass('has-error');
						$('.error-phone').text(data.errors.phone);
					} else if (data.errors.payroll) {
						$('.error-payroll').removeClass('hidden').addClass('text-danger');
						$('#payroll').addClass('has-error');
						$('.error-payroll').text(data.errors.payroll);
					} else if (data.errors.password) {
						$('.error-password').removeClass('hidden').addClass('text-danger');
						$('#password').addClass('has-error');
						$('.error-password').text(data.errors.password);
					}
				} else {
					console.log(data);
					location.reload();
				}
			},
		});
	});
</script>

resources/views/layouts/login.blade.php
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}"/>

<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- CSRF Token -->
<meta name="csrf-token" content="{{ csrf_token() }}">

<title>{{ config('app.name', 'MealBS') }}</title>

<link href="{{ asset('toastr/toastr.min.css') }}" rel="stylesheet" />
@toastr_css

<!-- Scripts -->

<link href="{{ asset('bucket/bs3/css/bootstrap.min.css') }}"
	rel="stylesheet">
<link href="{{ asset('bucket/css/bootstrap-reset.css') }}"
	rel="stylesheet">
<link href="{{ asset('bucket/font-awesome/css/font-awesome.css') }}"
	rel="stylesheet" />

<!-- Custom styles for this template -->
<link href="{{ asset('bucket/css/style.css') }}" rel="stylesheet">
<link href="{{ asset('bucket/css/style-responsive.css') }}"
	rel="stylesheet" />

</head>
</head>

<body class="login-body">
	<!-- BEGIN PAGE SPINNER -->
	<div class="page-spinner-bar" id="page-spinner-bar">
		<div class="bounce1"></div>
		<div class="bounce2"></div>
		<div class="bounce3"></div>
	</div>
	<!-- END PAGE SPINNER -->


	@jquery @toastr_js @toastr_render
	<!--  For toastr -->
	<script src="{{ asset('toastr/jquery.min.js') }}"></script>
	<script src="{{ asset('toastr/toastr.min.js') }}"></script>



	@yield('content')


	<script src="{{ asset('bucket/js/jquery.js') }}"></script>
	<script src="{{ asset('bucket/bs3/js/bootstrap.min.js') }}"></script>
	<script>
    	$(document).ready(function(){
    		$('.alert-success').fadeIn().delay(3000).fadeOut();
    		$('.alert-danger').fadeIn().delay(3000).fadeOut();
    		$('.alert-info').fadeIn().delay(3000).fadeOut();
          });
    </script>


	<script type="text/javascript">

         $(".reset-password").click(function() {
             $.ajax({
                 type: 'POST',
                 url: '{{ route('password-reset-local') }}',
                 data: {
                     '_token': $('input[name=_token]').val(),
                     'password': $('input[name=password]').val(),
                     'password_confirmation': $('input[name=password_confirmation]').val(),
                     'email': $('input[name=email]').val(),
                     'id': $('input[name=id]').val(),
                 },
                 success: function(data) {
                     if (data.errors) {
                         console.log(data.errors);
                         if (data.errors.email) {
                             $('.error-email').removeClass('hidden').addClass('text-danger');
                             $('#email').addClass('has-error');
                             $('.error-email').text(data.errors.email);
                         } else if (data.errors.password) {
                             $('.error-password').removeClass('hidden').addClass('text-danger');
                             $('#password').addClass('has-error');
                             $('.error-password').text(data.errors.password);
                         }else if (data.errors.password_confirmation) {
                             $('.error-password_confirmation').removeClass('hidden').addClass('text-danger');
                             $('#password_confirmation').addClass('has-error');
                             $('.error-password_confirmation').text(data.errors.password_confirmation);
                         }
                     } else {
                         console.log(data);
                         window.location.href= '/home';
                     }
                 },
             });
         });


		</script>
		
			<script type="text/javascript">
		toastr.options = {"closeButton":true,"closeClass":"toast-close-button","closeDuration":300,"closeEasing":"swing","closeHtml":"<button><i class=\"fa fa-times\"><\/i><\/button>","closeMethod":"fadeOut","closeOnHover":true,"containerId":"toast-container","debug":false,"escapeHtml":false,"extendedTimeOut":10000,"hideDuration":1000,"hideEasing":"linear","hideMethod":"fadeOut","iconClass":"toast-info","iconClasses":{"error":"toast-error","info":"toast-info","success":"toast-success","warning":"toast-warning"},"messageClass":"toast-message","newestOnTop":false,"onHidden":null,"onShown":null,"positionClass":"toast-top-center","preventDuplicates":true,"progressBar":true,"progressClass":"toast-progress","rtl":false,"showDuration":300,"showEasing":"swing","showMethod":"fadeIn","tapToDismiss":true,"target":"body","timeOut":5000,"titleClass":"toast-title","toastClass":"toast"};
	</script>


</body>

</html>

resources/views/layouts/sidebar.blade.php
<aside>
            <div id="sidebar" class="nav-collapse">
                <!-- sidebar menu start-->
                <div class="leftside-navigation">
                    <ul class="sidebar-menu" id="nav-accordion">
                        {{-- Modules Load --}}
                        @foreach($modules as $module)
                        @can('view-'.$module->title, 'view-'.$module->title)
                        <li>
                            <a href="{{ route($module->link, ['id'=> $module->id]) }}">
                            <i class="{{$module->icon}}"></i>
                                <span>{{$module->title}}</span>
                            </a>
                            <?php $children = $module->children; ?>
                            @if($children)
                                @foreach($children as $child)
                                    <ul class="sub" style="display: block;">
                                	@can('view-'.$child->title, 'view-'.$child->title)
                                        <li><a href="{{ route($child->link, ['id'=> $child->id]) }}"><i class="{{$child->icon}}"></i>{{$child->title}}</a></li>
                                    @endcan
                                    </ul>
                                @endforeach
                             @endif
                        </li>
                        @endcan
                        @endforeach
                        
                          <li>
                          <a href="{{ route('logout') }}"
                                onclick="event.preventDefault(); document.getElementById('logout-form').submit();"><i
                                    class="fa fa-user"></i> Log Out</a>
                          </li>
                    </ul>
                </div>
                <!-- sidebar menu end-->
            </div>
        </aside>
        <!--sidebar end-->

resources/views/layouts/sidebarStatic.blade.php
<aside>
	<div id="sidebar" class="nav-collapse">
		<!-- sidebar menu start-->
		<div class="leftside-navigation">

			<ul class="sidebar-menu" id="nav-accordion">
				<li><a href="{{ route('home') }}"> <i class="fa fa-dashboard"></i> <span>Dashboard</span>
				</a></li>
				<li class="sub-menu"><a href="javascript:;"> <i class="fa fa-laptop"></i>
						<span>Menu</span>
				</a>
					<ul class="sub">
						<li><a href="{{ route('menu.index') }}">Menu</a></li>
						<li><a href="{{ route('menu_calendar') }}">Menu Calendar</a></li>
					</ul></li>
				<li class="sub-menu"><a href="javascript:;" class=""> <i
						class="fa fa-book"></i> <span>Booking</span>
				</a>
					<ul class="sub">
						<li><a href="{{ route('booking.index') }}">Meal Booking</a></li>
						<li><a href="{{ route('booking_admin.index') }}">Admin Booking</a></li>
					</ul></li>
				<li class="sub-menu"><a href="javascript:;"> <i
						class="fa fa-envelope"></i> <span>SMS</span>
				</a>
					<ul class="sub">
						<li><a href="{{ route('sms.index') }}">SMS Reminders</a></li>
					</ul></li>
				<li class="sub-menu"><a href="javascript:;"> <i class="fa fa-tasks"></i>
						<span>Administration</span>
				</a>
					<ul class="sub">
						<li><a href="{{ route('meal.index') }}">Meals</a></li>
						<li><a href="{{ route('user.index') }}">Users</a></li>
						<li><a href="{{ route('right.index') }}">User Rights</a></li>
						<li><a href="{{ route('user_group.index') }}">User Groups</a></li>
						<li><a href="{{ route('booking.index') }}">Bookings</a></li>
						<li><a href="{{ route('menu.index') }}">Menu Setup</a></li>
						<li><a href="{{ route('student.index') }}">Students</a></li>
						<li><a href="{{ route('caterer.index') }}">Caterers</a></li>
						<li><a href="{{ route('visitor.index') }}">Visitors</a></li>
					</ul></li>
				<li class="sub-menu"><a href="javascript:;"> <i
						class=" fa fa-bar-chart-o"></i> <span>Reports</span>
				</a>
					<ul class="sub">
						<li><a href="{{ route('report_meal') }}">Booking Report</a></li>
						<!--                                 <li><a href="">Today Booked Meals</a></li> -->
					</ul></li>

				<li><a href="login.html"
					onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
						<i class="fa fa-user"></i> <span>Logout</span>
				</a></li>
			</ul>
		</div>
		<!-- sidebar menu end-->
	</div>
</aside>
<!--sidebar end-->